AUTH0_CLIENT_ID = '2aDw62bnurCjiOeAz0TjSphKWRtuNIL6'
AUTH0_CLIENT_SECRET = 'oI3llTVdQQyhElbH4j2d311h1_cP-Xp_WuN569jV6rDbOifA8SQiQSUAGQ_RvyQL'
AUTH0_CALLBACK_URL = 'AUTH0_CALLBACK_URL'
AUTH0_DOMAIN = 'dev-psgi167i.us.auth0.com'
AUTH0_AUDIENCE = 'AUTH0_AUDIENCE'
PROFILE_KEY = 'profile'
SECRET_KEY = 'ThisIsTheSecretKey'
JWT_PAYLOAD = 'jwt_payload'

